### ISSUE TITLE
Search page - Improvements

### ISSUE THREAD

**Issue by sasastevcic** [petramarkovic/news#24]
It might make more sense to search on a keystroke with debounce

Better UX flow:
- User lands on a page it shows empty page or some message for user to start typing
- As soon as user starts typing we see skeleton
- If there are results and user starts typing again, we should see loading spinner next to the search icon
- If there is no results with specific query, user should see a some no results message

Nice to have:
- Add query term to search param eg /search?query=Something. If you reload the page you should fetch data with specific query

**Comment by petramarkovic** [comment]
To do: finish nice to have option
